language: r
cache: packages
warnings_are_errors: false

r:
  - oldrel
  - release
  - devel

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

notifications:
  email:
  on_success: never
  on_failure: never