repos:
  CRAN: https://cran.rstudio.com

warnings_are_errors: false

deploy.skip_cleanup: true

os:
  - linux

sudo: true
dist: bionic

cache:
  - packages

sudo: true
before_install:
  - sudo apt-get install jags
  - sudo apt-get install r-cran-rjags

latex: true
pandoc: true

notifications:
  email:
  on_success: never
  on_failure: never